# Generated by Django 3.2.7 on 2021-09-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('data', models.JSONField()),
                ('timestamp', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'event_log',
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['name', 'category', 'session_id'], name='event_log_name_252699_idx'),
        ),
    ]
